editor_homepage:
    path:     /
    defaults: { _controller: EditorBundle:Editor:index }

editor_persist_json:
    path:     /persist-blocs
    defaults: { _controller: EditorBundle:Editor:persistJson }
