editor_homepage:
    path:     /
    defaults: { _controller: EditorBundle:Editor:index }

editor_persist_json:
    path:     /persist-blocs
    defaults: { _controller: EditorBundle:Editor:persistJson }

editor_save_component:
    path:     /save-component
    defaults: { _controller: EditorBundle:Editor:saveComponent }
